# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('solicitation_date', models.DateTimeField(verbose_name='solicitation date')),
                ('response_date', models.DateTimeField(verbose_name='response due date')),
            ],
        ),
    ]
